version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'prodDetails'
#      MYSQL_USER: 'root'  # It's recommended to use a non-root user for applications
#      MYSQL_PASSWORD: 'Amry@0302'
      MYSQL_ROOT_PASSWORD: 'Amry@0302'  # Root password, use a secure one
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/prodDetails?enabledTLSProtocols=TLSv1.2
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Amry@0302'
    ports:
      - "9191:9191"
    restart: always

volumes:
  db-data: